/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gpacalculator;

import java.awt.event.ItemEvent;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author J3ranch
 */
public class GPAView extends javax.swing.JFrame {
    
    private GPAController controller = new GPAController();

    /**
     * Creates new form GPAView
     */
    
    private JLabel[] jLabelsAddForm = {new JLabel("Class Name"), new JLabel("Grade"), new JLabel("Honors/AP?")};
    private JTextField jTextFieldClass = new JTextField();
    private JComboBox jComboBoxGrade = new JComboBox(Grade.LETTER_GRADES);
    private JCheckBox jCheckBoxHonors = new JCheckBox();
    
    public GPAView() {
        // Initialize JComponents
        initComponents();
        
        // Format columns of jTableGrades
        jTableGrades.getColumnModel().getColumn(0).setResizable(false);
        jTableGrades.getColumnModel().getColumn(0).setMinWidth(jTableGrades.getWidth() / 2);
        jTableGrades.getColumnModel().getColumn(1).setResizable(false);
        jTableGrades.getColumnModel().getColumn(2).setResizable(false);
        jTableGrades.getColumnModel().getColumn(3).setResizable(false);
    }
    
    private void updateGPA() {
        jLabelTotalGPA.setText(String.format("Total GPA: %4.02f", controller.calculateGPA()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupWeight = new javax.swing.ButtonGroup();
        jScrollPaneGrades = new javax.swing.JScrollPane();
        jTableGrades = new javax.swing.JTable();
        jLabelWeightOption = new javax.swing.JLabel();
        jRadioButtonUnweighted = new javax.swing.JRadioButton();
        jRadioButtonWeighted = new javax.swing.JRadioButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelTotalGPA = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPaneGrades.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneGrades.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableGrades.setModel(controller.getGPATable());
        jTableGrades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableGrades.setShowVerticalLines(false);
        jTableGrades.getTableHeader().setReorderingAllowed(false);
        jScrollPaneGrades.setViewportView(jTableGrades);

        jLabelWeightOption.setText("Grade Weight:");

        buttonGroupWeight.add(jRadioButtonUnweighted);
        jRadioButtonUnweighted.setSelected(true);
        jRadioButtonUnweighted.setText("Unweighted");
        jRadioButtonUnweighted.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonUnweightedItemStateChanged(evt);
            }
        });

        buttonGroupWeight.add(jRadioButtonWeighted);
        jRadioButtonWeighted.setText("Weighted");
        jRadioButtonWeighted.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonWeightedItemStateChanged(evt);
            }
        });

        jButtonAdd.setText("Add Grade");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit Grade");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonRemove.setText("Remove Grade");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear All");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabelTotalGPA.setText("Total GPA:  NaN");

        jButtonHome.setText("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTotalGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPaneGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelWeightOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonUnweighted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonWeighted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHome)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWeightOption)
                            .addComponent(jRadioButtonUnweighted)
                            .addComponent(jRadioButtonWeighted)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonHome)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonRemove)
                    .addComponent(jButtonClear)
                    .addComponent(jLabelTotalGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // Get selected row index
        int selectedRow = jTableGrades.getSelectedRow();
        
        // Return if nothing is selected
        if (selectedRow == -1)
            return;
        
        // Confirm remove
        int i = JOptionPane.showOptionDialog(this, "Remove selected Grade?", "Confirm Remove Grade", 
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"Confirm", "Cancel"}, null);
        
        // Remove grade at selected row index and update GPA
        if (i == JOptionPane.OK_OPTION)
            controller.removeGrade(jTableGrades.getSelectedRow());
        updateGPA();
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // Confirm clear all
        int i = JOptionPane.showOptionDialog(this, "Clear All?", "Confirm Clear All", 
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"Confirm", "Cancel"}, null);
        
        // Clear all grades if user confirms
        if (i == JOptionPane.OK_OPTION)
            controller.clearData();
        
        // Update GPA
        updateGPA();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // Components for Add Form dialog
        JLabel[] jLabelsAddForm = {new JLabel("Class Name"), new JLabel("Grade"), new JLabel("Honors/AP?")};
        JTextField jTextFieldClass = new JTextField();
        JComboBox jComboBoxGrade = new JComboBox(Grade.LETTER_GRADES);
        JCheckBox jCheckBoxHonors = new JCheckBox();
        
        // Receive user input via dialog
        int i = JOptionPane.showOptionDialog(this, new Object[]{jLabelsAddForm[0], jTextFieldClass, jLabelsAddForm[1], jComboBoxGrade, jLabelsAddForm[2], jCheckBoxHonors},
                                            "Add New Grade", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Add", "Cancel"}, null);
        
        // Add grade if user confirms
        if (i == JOptionPane.OK_OPTION)
            controller.addGrade(jTextFieldClass.getText(), jComboBoxGrade.getItemAt(jComboBoxGrade.getSelectedIndex()).toString(), jCheckBoxHonors.isSelected());
        
        // Scroll to bottom to make new grade visible and update GPA
        jTableGrades.scrollRectToVisible(jTableGrades.getCellRect(jTableGrades.getRowCount() - 1, 0, true));
        updateGPA();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jRadioButtonUnweightedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonUnweightedItemStateChanged
        // Changes weighted status to false and updates GPA
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            controller.setWeightedStatus(false);
        }
        updateGPA();
    }//GEN-LAST:event_jRadioButtonUnweightedItemStateChanged

    private void jRadioButtonWeightedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonWeightedItemStateChanged
        // Changes weighted status to true and updates GPA
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            controller.setWeightedStatus(true);
        }
        updateGPA();
    }//GEN-LAST:event_jRadioButtonWeightedItemStateChanged

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // Components for Edit Form dialog
        JLabel[] jLabelsEditForm = {new JLabel("Class Name"), new JLabel("Grade"), new JLabel("Honors/AP?")};
        JTextField jTextFieldClass;
        JComboBox jComboBoxGrade = new JComboBox(Grade.LETTER_GRADES);
        JCheckBox jCheckBoxHonors;
        
        // Get selected row index
        int selectedRow = jTableGrades.getSelectedRow();
        
        // Return if nothing is selected
        if (selectedRow == -1)
            return;
        
        // Attempt to get existing values, return if not possible
        try {
            jTextFieldClass = new JTextField(controller.getClassNameAt(selectedRow));
            jComboBoxGrade.setSelectedItem(controller.getLetterGradeAt(selectedRow));
            jCheckBoxHonors = new JCheckBox((String) null, controller.getHonorsAt(selectedRow));
        } catch (Exception e) {
            return;
        }
        
        // If existing data is retrieved, create Edit Form dialog and retrieve user input
        int i = JOptionPane.showOptionDialog(this, new Object[]{jLabelsEditForm[0], jTextFieldClass, jLabelsEditForm[1], jComboBoxGrade, jLabelsEditForm[2], jCheckBoxHonors},
                                            "Edit Existing Grade", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Confirm"}, "Confirm");
        
        // If user confirms, edit existing grade
        if (i == JOptionPane.OK_OPTION) {
            controller.editGradeAt(selectedRow, jTextFieldClass.getText(), jComboBoxGrade.getItemAt(jComboBoxGrade.getSelectedIndex()).toString(), jCheckBoxHonors.isSelected());
        }
        
        // Update GPA
        updateGPA();
    }//GEN-LAST:event_jButtonEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupWeight;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabelTotalGPA;
    private javax.swing.JLabel jLabelWeightOption;
    private javax.swing.JRadioButton jRadioButtonUnweighted;
    private javax.swing.JRadioButton jRadioButtonWeighted;
    private javax.swing.JScrollPane jScrollPaneGrades;
    private javax.swing.JTable jTableGrades;
    // End of variables declaration//GEN-END:variables
}
